# Generated by Django 3.0.6 on 2020-05-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramblings', '0006_post_permlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='permlink',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
    ]
