# Generated by Django 3.0.6 on 2020-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramblings', '0007_auto_20200515_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
