# Generated by Django 3.0.6 on 2020-05-17 12:37

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ramblings', '0010_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ramblings.Post'),
        ),
    ]
