# Generated by Django 3.0.6 on 2020-05-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramblings', '0012_auto_20200517_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reply_to',
            new_name='parent',
        ),
    ]
